var Next1 = document.getElementById("Next1");
var Back1 = document.getElementById("Back1");
var Next2 = document.getElementById("Next2");
var Back2 = document.getElementById("Back2");
var Next3 = document.getElementById("Next3");
var Back3 = document.getElementById("Back3");
var Next4 = document.getElementById("Next4");
var Back4 = document.getElementById("Back4");
var Next5 = document.getElementById("Next5");
var Back5 = document.getElementById("Back5");
var button1 = document.getElementById("button1");
var button2 = document.getElementById("button2");
var button3 = document.getElementById("button3");
var button4 = document.getElementById("button4");
var button5 = document.getElementById("button5");
var button6 = document.getElementById("button6");
var button7 = document.getElementById("button7");
var button8 = document.getElementById("button8");
var button9 = document.getElementById("button9");
var button10 = document.getElementById("button10");
var button11 = document.getElementById("button11");
var button12 = document.getElementById("button12");
var button13 = document.getElementById("button13");
var button14 = document.getElementById("button14");
var button15 = document.getElementById("button15");
var button16 = document.getElementById("button16");
var button17 = document.getElementById("button17");
var button18 = document.getElementById("button18");
var button19 = document.getElementById("button19");
var button20 = document.getElementById("button20");
var button21= document.getElementById("button21");
var button22 = document.getElementById("button22");
var button23 = document.getElementById("button23");
var button24 = document.getElementById("button24");
var button25 = document.getElementById("button25");
var button26 = document.getElementById("button26");
var button27 = document.getElementById("button27");
var button28 = document.getElementById("button28");
var button29 = document.getElementById("button29");
var button30 = document.getElementById("button30");
var button31 = document.getElementById("button31");
var button32 = document.getElementById("button32");
var button33 = document.getElementById("button33");
var button34 = document.getElementById("button34");
var button35 = document.getElementById("button35");
var button36 = document.getElementById("button36");

    Next1.onclick = function(){
        Next1.style.display = "none";
        Back1.style.display = "block";
        Next2.style.display = "block";
        button1.style.left = "-400px";
        button2.style.left = "-400px";
        button3.style.left = "-400px";
        button4.style.left = "-400px";
        button5.style.left = "-400px";
        button6.style.left = "-400px";
        button7.style.left = "-400px";
        button8.style.left = "5%";
        button9.style.left = "5%";
        button10.style.left = "5%";
        button11.style.left = "5%";
        button12.style.left = "5%";
        button13.style.left = "5%";
        button14.style.left = "5%";
    }
        Back1.onclick = function(){
            Next1.style.display = "block";
            Back1.style.display = "none";
            Next2.style.display = "none";
            button1.style.left = "5%";
            button2.style.left = "5%";
            button3.style.left = "5%";
            button4.style.left = "5%";
            button5.style.left = "5%";
            button6.style.left = "5%";
            button7.style.left = "5%";
            button8.style.left = "400px";
            button9.style.left = "400px";
            button10.style.left = "400px";
            button11.style.left = "400px";
            button12.style.left = "400px";
            button13.style.left = "400px";
            button14.style.left = "400px";
        }

        Next2.onclick = function(){
            Next2.style.display = "none";
            Next3.style.display = "block";
            Back2.style.display = "block";
            Back1.style.display = "none";
            button8.style.left = "-400px";
            button9.style.left = "-400px";
            button10.style.left = "-400px";
            button11.style.left = "-400px";
            button12.style.left = "-400px";
            button13.style.left = "-400px";
            button14.style.left = "-400px";
            button15.style.left = "5%";
            button16.style.left = "5%";
            button17.style.left = "5%";
            button18.style.left = "5%";
            button19.style.left = "5%";
            button20.style.left = "5%";
            button21.style.left = "5%";
        }
        Back2.onclick = function(){
            Next2.style.display = "block";
            Next3.style.display = "none";
            Back2.style.display = "none";
            Back1.style.display = "block";
            button15.style.left = "400px";
            button16.style.left = "400px";
            button17.style.left = "400px";
            button18.style.left = "400px";
            button19.style.left = "400px";
            button20.style.left = "400px";
            button21.style.left = "400px";
            button8.style.left = "5%";
            button9.style.left = "5%";
            button10.style.left = "5%";
            button11.style.left = "5%";
            button12.style.left = "5%";
            button13.style.left = "5%";
            button14.style.left = "5%";
        }

        Next3.onclick = function(){
            Next3.style.display = "none";
            Next4.style.display = "block";
            Back2.style.display = "none";
            Back3.style.display = "block";
            button15.style.left = "-400px";
            button16.style.left = "-400px";
            button17.style.left = "-400px";
            button18.style.left = "-400px";
            button19.style.left = "-400px";
            button20.style.left = "-400px";
            button21.style.left = "-400px";
            button22.style.left = "5%";
            button23.style.left = "5%";
            button24.style.left = "5%";
            button25.style.left = "5%";
            button26.style.left = "5%";
            button27.style.left = "5%";
            button28.style.left = "5%";
        }
        Back3.onclick = function(){
            Next3.style.display = "block";
            Next4.style.display = "none";
            Back2.style.display = "block";
            Back3.style.display = "none";
            button22.style.left = "400px";
            button23.style.left = "400px";
            button24.style.left = "400px";
            button25.style.left = "400px";
            button26.style.left = "400px";
            button27.style.left = "400px";
            button28.style.left = "400px";
            button15.style.left = "5%";
            button16.style.left = "5%";
            button17.style.left = "5%";
            button18.style.left = "5%";
            button19.style.left = "5%";
            button20.style.left = "5%";
            button21.style.left = "5%";
        }

        Next4.onclick = function(){
            Back3.style.display = "none";
            Back4.style.display = "block";
            Next4.style.display = "none";
            Next5.style.display = "block";
            button29.style.left = "5%";
            button30.style.left = "5%";
            button31.style.left = "5%";
            button32.style.left = "5%";
            button33.style.left = "5%";
            button34.style.left = "5%";
            button35.style.left = "5%";
            button22.style.left = "-400px";
            button23.style.left = "-400px";
            button24.style.left = "-400px";
            button25.style.left = "-400px";
            button26.style.left = "-400px";
            button27.style.left = "-400px";
            button28.style.left = "-400px";
        }
        Back4.onclick = function(){
            Next4.style.display = "block";
            Back4.style.display = "none";
            Next5.style.display = "none";
            Back3.style.display = "block";
            button29.style.left = "400px";
            button30.style.left = "400px";
            button31.style.left = "400px";
            button32.style.left = "400px";
            button33.style.left = "400px";
            button34.style.left = "400px";
            button35.style.left = "400px";
            button22.style.left = "5%";
            button23.style.left = "5%";
            button24.style.left = "5%";
            button25.style.left = "5%";
            button26.style.left = "5%";
            button27.style.left = "5%";
            button28.style.left = "5%";
        }
        
        Next5.onclick = function(){
            Next5.style.display = "none";
            Back4.style.display = "none";
            Back5.style.display = "block";
            button36.style.left = "5%";
            button29.style.left = "-400px";
            button30.style.left = "-400px";
            button31.style.left = "-400px";
            button32.style.left = "-400px";
            button33.style.left = "-400px";
            button34.style.left = "-400px";
            button35.style.left = "-400px";
        }
        Back5.onclick = function(){
            Next5.style.display = "block";
            Back5.style.display = "none";
            Back4.style.display = "block";
            button36.style.left = "400px";
            button29.style.left = "5%";
            button30.style.left = "5%";
            button31.style.left = "5%";
            button32.style.left = "5%";
            button33.style.left = "5%";
            button34.style.left = "5%";
            button35.style.left = "5%";
        }